# SwiftLint Configuration for Sprung

# Paths to exclude from linting
excluded:
  - build
  - .build
  - DerivedData
  - Carthage
  - Pods
  - .bundle
  - vendor
  - fastlane
  - '**/build/**'
  - '**/SourcePackages/**'

# Paths to include (only your source files)
included:
  - Sprung

# Enabled rules
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_first_last
  - closure_spacing
  - contains_over_first_not_nil

# Disabled rules (uncomment to disable specific rules)
disabled_rules:
  - line_length  # Disabled - not valuable for codebase with lots of LLM prompts/descriptions
  # - trailing_whitespace  # We'll fix this with auto-fix first

# Customize rule configurations
# line_length:  # DISABLED - see disabled_rules above
#   warning: 140  # More reasonable than 120 for modern screens
#   error: 200
#   ignores_function_declarations: true
#   ignores_comments: true
#   ignores_urls: true

file_length:
  warning: 500  # Slightly more lenient
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 120

type_body_length:
  warning: 300
  error: 400

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 12
  error: 20
  ignores_case_statements: true

nesting:
  type_level: 2
  function_level: 3

identifier_name:
  min_length:
    warning: 2  # Allow 2-char names like 'id'
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - i
    - j
    - k
    - x
    - y
    - z
    - id
    - db
    - to
    - at
    - df
    - ok

# Warnings to treat as errors (when ready for stricter enforcement)
# strict: true

# Report format
reporter: "xcode"
