# SwiftLint Configuration for Sprung

# Paths to exclude from linting
excluded:
  - build
  - .build
  - DerivedData
  - Carthage
  - Pods
  - .bundle
  - vendor
  - fastlane
  - '**/build/**'
  - '**/SourcePackages/**'

# Paths to include (only your source files)
included:
  - Sprung

# Enabled rules
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_first_last
  - closure_spacing
  - contains_over_first_not_nil

# Disabled rules
disabled_rules:
  - line_length  # Not valuable for codebase with lots of LLM prompts/descriptions
  - multiple_closures_with_trailing_closure  # Common SwiftUI pattern, not harmful
  - nesting  # SwiftUI views often require nested closures
  - large_tuple  # Sometimes tuples are pragmatic for internal use

# Customize rule configurations
# line_length:  # DISABLED - see disabled_rules above
#   warning: 140  # More reasonable than 120 for modern screens
#   error: 200
#   ignores_function_declarations: true
#   ignores_comments: true
#   ignores_urls: true

file_length:
  warning: 600
  error: 1200
  ignore_comment_only_lines: true

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 500
  error: 800

function_parameter_count:
  warning: 8
  error: 10

cyclomatic_complexity:
  warning: 15
  error: 30
  ignores_case_statements: true

identifier_name:
  min_length:
    warning: 1  # Allow single-char names in loops/closures
    error: 0
  max_length:
    warning: 60
    error: 80
  excluded:
    - i
    - j
    - k
    - n
    - s
    - t
    - u
    - v
    - x
    - y
    - z
    - id
    - db
    - to
    - at
    - df
    - ok

type_name:
  # Allow underscore-prefixed names for internal LLM implementation types
  # These types are deliberately named with _ prefix to signal they should
  # not be used directly - use LLMFacade instead
  excluded:
    - _LLMRequestExecutor
    - _LLMService
    - _LLMRequestBuilder
    - _StreamingExecutor
    - _FlexibleJSONExecutor
    - _JSONResponseParser
    - _LLMVendorMapper
    - _SwiftOpenAIClient
    - _OpenAIResponsesClient
    - _OpenAIResponsesConversationService

# Warnings to treat as errors (when ready for stricter enforcement)
# strict: true

# Report format
reporter: "xcode"
