//
//  ArtifactStorageProtocol.swift
//  Sprung
//
//  Protocol for artifact storage, enabling both onboarding (ArtifactRepository)
//  and standalone ingestion (InMemoryArtifactRepository) to work with
//  SubAgentToolExecutor and KC generation services.
//

import Foundation
import SwiftyJSON

/// Protocol for artifact storage used by sub-agent tool executors and KC generation.
/// Provides read access to artifacts and temporary storage for pending knowledge cards.
protocol ArtifactStorageProtocol: Actor {
    /// Get artifact record by ID (for SubAgentToolExecutor.get_artifact)
    func getArtifactRecord(id: String) async -> JSON?

    /// Add a new artifact record
    func addArtifactRecord(_ artifact: JSON) async

    /// Store a pending knowledge card (generated by KC agent, not yet persisted)
    func storePendingCard(_ card: JSON, id: String) async

    /// Retrieve a pending knowledge card by ID
    func getPendingCard(id: String) async -> JSON?
}
