//
//  DocumentSummary.swift
//  Sprung
//
//  Structured summary of a document generated during ingestion.
//  Used to provide lightweight context to the main LLM coordinator
//  without requiring full document text.
//

import Foundation

/// Structured summary of a document for the multi-agent architecture.
/// Generated by the Anthropic document-analysis summary pass during ingestion.
struct DocumentSummary: Codable {
    /// Type of document (resume, performance_review, project_doc, etc.)
    let documentType: String

    /// Brief one-line description (~10 words) for quick reference
    let briefDescription: String

    /// ~500 word narrative summary of the document content
    let summary: String

    /// Time period covered by the document (e.g., "2019-2023")
    let timePeriod: String?

    /// Companies mentioned in the document
    let companies: [String]

    /// Roles/positions mentioned
    let roles: [String]

    /// Skills identified in the document
    let skills: [String]

    /// Key achievements mentioned
    let achievements: [String]

    /// Hints about what types of knowledge cards this doc could support
    let relevanceHints: String
}
