//
//  InferenceGuidanceListView.swift
//  Sprung
//
//  List view for managing inference guidance records.
//  Allows enabling/disabling and editing guidance.
//

import SwiftUI

struct InferenceGuidanceListView: View {
    @Environment(InferenceGuidanceStore.self) private var store
    @State private var selectedGuidance: InferenceGuidance?
    @State private var showingTitleSetEditor = false

    var body: some View {
        VStack(spacing: 0) {
            if store.allGuidance.isEmpty {
                emptyStateView
            } else {
                guidanceList
            }
        }
        .navigationTitle("Inference Guidance")
        .toolbar {
            ToolbarItem(placement: .primaryAction) {
                Menu {
                    Button("Title Sets") {
                        showingTitleSetEditor = true
                    }
                    Divider()
                    Button("Delete All Auto-Generated", role: .destructive) {
                        store.deleteAutoGenerated()
                    }
                    .disabled(!store.hasAutoGeneratedGuidance)
                } label: {
                    Image(systemName: "ellipsis.circle")
                }
            }
        }
        .sheet(isPresented: $showingTitleSetEditor) {
            TitleSetEditorView()
        }
        .sheet(item: $selectedGuidance) { guidance in
            GuidanceDetailView(guidance: guidance)
        }
    }

    private var emptyStateView: some View {
        VStack(spacing: 16) {
            Image(systemName: "text.badge.star")
                .font(.system(size: 48))
                .foregroundStyle(.secondary)
            Text("No Inference Guidance")
                .font(.headline)
            Text("Guidance is automatically generated during onboarding to help customize your resume.")
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
                .frame(maxWidth: 300)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    private var guidanceList: some View {
        List(selection: $selectedGuidance) {
            if !store.enabledGuidance.isEmpty {
                Section("Active Guidance") {
                    ForEach(store.enabledGuidance) { guidance in
                        GuidanceRow(guidance: guidance)
                    }
                }
            }

            let disabledGuidance = store.allGuidance.filter { !$0.isEnabled }
            if !disabledGuidance.isEmpty {
                Section("Disabled") {
                    ForEach(disabledGuidance) { guidance in
                        GuidanceRow(guidance: guidance)
                            .opacity(0.6)
                    }
                }
            }
        }
    }
}

struct GuidanceRow: View {
    let guidance: InferenceGuidance
    @Environment(InferenceGuidanceStore.self) private var store

    var body: some View {
        HStack {
            VStack(alignment: .leading, spacing: 4) {
                Text(guidance.displayName)
                    .font(.headline)
                Text(guidance.nodeKey)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            Spacer()

            // Source badge
            Text(guidance.source.rawValue.uppercased())
                .font(.caption2)
                .fontWeight(.medium)
                .padding(.horizontal, 6)
                .padding(.vertical, 2)
                .background(guidance.source == .auto ? Color.blue.opacity(0.2) : Color.green.opacity(0.2))
                .foregroundStyle(guidance.source == .auto ? Color.blue : Color.green)
                .cornerRadius(4)

            // Enable toggle
            Toggle("", isOn: Binding(
                get: { guidance.isEnabled },
                set: { _ in store.toggleEnabled(guidance) }
            ))
            .labelsHidden()
        }
        .padding(.vertical, 4)
    }
}
