//
//  CoverLetterStore.swift
//  PhysCloudResume
//
//  Created by Christopher Culbreath on 9/12/24.
//

//
//  swift
//  PhysicsCloudResume
//
//  Created by Christopher Culbreath on 8/30/24.
//

import Foundation
import SwiftData

// Replaces hand‑rolled `saveContext()` duplication with a shared helper.
import SwiftUI // Needed only for `@Observable` macro, already available.

@Observable
@MainActor
final class CoverLetterStore: SwiftDataStore {
    // MARK: - Properties

    unowned let modelContext: ModelContext
    var coverRefStore: CoverRefStore
    var cL: CoverLetter? // This is the currently selected/active cover letter instance
    private let exportService = LocalCoverLetterExportService()

    // MARK: - Initialiser

    init(context: ModelContext, refStore: CoverRefStore) {
        modelContext = context
        coverRefStore = refStore

        // Perform one-time migration for existing cover letters
        performMigrationForGeneratedFlag()
    }

    @discardableResult
    func addLetter(letter: CoverLetter, to jobApp: JobApp) -> CoverLetter {
        jobApp.coverLetters.append(letter)
        jobApp.selectedCover = letter // Set the newly added letter as selected
        modelContext.insert(letter)
        //    saveContext() // Context will be saved by the caller or at appropriate points
        return letter
    }

    func createBlank(jobApp: JobApp) {
        let letter = CoverLetter(
            enabledRefs: coverRefStore.defaultSources, // Start with default refs
            jobApp: jobApp
        )
        letter.generated = false // A blank letter is not yet generated
        // Do not set a name for a blank letter initially.
        // It will be named upon first generation or if the user manually edits and saves.
        jobApp.coverLetters.append(letter)
        jobApp.selectedCover = letter // Select the new blank letter

        modelContext.insert(letter)
        // saveContext() // Avoid saving context here; let higher-level operations manage saves.
    }

    @discardableResult
    func create(jobApp: JobApp) -> CoverLetter {
        let letter = CoverLetter(
            enabledRefs: coverRefStore.defaultSources,
            jobApp: jobApp
        )
        // Name will be set by processResults after AI generation.
        // includeResumeRefs will also be handled by the generation logic.
        modelContext.insert(letter)
        //      try? modelContext.save()
        return letter
    }

    func createDuplicate(letter: CoverLetter) -> CoverLetter {
        // Ensure the context has pending changes saved before duplicating,
        // especially if the original letter might have unsaved modifications.
        saveContext() // From `SwiftDataStore` extension

        let newLetter = CoverLetter(
            enabledRefs: letter.enabledRefs, // Copy enabled references
            jobApp: letter.jobApp // Associate with the same job application
        )
        newLetter.includeResumeRefs = letter.includeResumeRefs // Preserve this flag
        newLetter.content = letter.content // Copy content for revision
        newLetter.generated = false // A duplicated letter for revision starts as not "freshly" generated by AI
        // It will be marked true by processResults after the revision.
        newLetter.encodedMessageHistory = letter.encodedMessageHistory // Copy message history for context
        newLetter.currentMode = letter.currentMode // Copy current mode

        // Preserve the existing cover letter name for revision operations.
        // The revision type (e.g., "zissner") will be appended by processResults.
        newLetter.name = letter.name

        // Copy other necessary properties here if any

        if let jobApp = letter.jobApp {
            addLetter(letter: newLetter, to: jobApp) // This also sets it as selectedCover on jobApp
        }
        // saveContext() // Context will be saved by the caller or at appropriate points
        return newLetter
    }

    func deleteLetter(_ letter: CoverLetter) {
        if let jobApp = letter.jobApp {
            if let index = jobApp.coverLetters.firstIndex(of: letter) {
                jobApp.coverLetters.remove(at: index)
                modelContext.delete(letter)
                //      saveContext() // Context will be saved by the caller
            }
        } else {
            // If the letter is not associated with a jobApp, just delete it.
            // This case should ideally not happen if data integrity is maintained.
            modelContext.delete(letter)
            // saveContext()
        }
    }

    // `saveContext()` now provided by `SwiftDataStore` default implementation.

    // MARK: - PDF Export

    func exportPDF(from coverLetter: CoverLetter) -> Data {
        return exportService.exportPDF(from: coverLetter, applicant: Applicant())
    }

    func exportAllCoverLetters(for jobApp: JobApp) -> [Data] {
        return jobApp.coverLetters.filter { $0.generated }.map { letter in
            exportService.exportPDF(from: letter, applicant: Applicant())
        }
    }

    // MARK: - Migration

    /// One-time migration to set generated = true for all existing cover letters with content
    @MainActor
    private func performMigrationForGeneratedFlag() {
        // Use AppStorage to track migration status
        let migrationKey = "CoverLetterGeneratedFlagMigrationCompleted"
        let defaults = UserDefaults.standard

        // Only run migration once
        if defaults.bool(forKey: migrationKey) {
            return
        }

        do {
            // Fetch all cover letters
            let descriptor = FetchDescriptor<CoverLetter>()
            let allCoverLetters = try modelContext.fetch(descriptor)

            var updatedCount = 0

            // Update only those with content but not marked as generated
            for letter in allCoverLetters {
                if !letter.content.isEmpty && !letter.generated {
                    letter.generated = true
                    updatedCount += 1
                }
            }

            if updatedCount > 0 {
                print("Migration: Set generated=true for \(updatedCount) cover letters with content")
                saveContext()
            }

            // Mark migration as completed
            defaults.set(true, forKey: migrationKey)

        } catch {
            print("Failed to perform cover letter migration: \(error.localizedDescription)")
        }
    }
}
